fix typo

diff --git a/lab4/untrash b/lab4/untrash
--- a/lab4/untrash
+++ b/lab4/untrash
@@ -4,14 +4,14 @@ filename=$1
 home="/home/user"
 
 printError() {
-echo -e "untrash: error\nUsage: untrash FILENAME\nError: "$1
-exit 1
+	echo -e "untrash: error\nUsage: untrash FILENAME\nError: "$1
+	exit 1
 }
 
 #check amount
 if (( $# != 1 ))
 then
-printError "expected exactly one argument"
+	printError "expected exactly one argument"
 fi
 
 log=$(awk '{print $1":"$2}' $home/.trash.log)
@@ -55,9 +55,10 @@ do
 				fi
 				ln $home/.trash/$id $pathDir/$pathFile
 				rm $home/.trash/$id
-				echo "Recovered as '"$pathFile"' successful"
+				echo "File '"$path"' recovered as '"$pathFile"'"
 				break
 			done
+
 			echo "Continue scanning for '"$filename"' entries? [y/N]"
 			while [[ true ]]
 			do
